namespace Campaign;

public enum PlaceKind
{
    City,
    Port,
    Sanctuary,
    Ruin,
    Mark
}

public readonly record struct EarthPlace(
    string Name,
    string Polity,
    float Lon,
    float Lat,
    PlaceKind Kind,
    string Sphere);

/// <summary>
/// Named sites of about 300 BCE — after Alexander, before Qin unified China,
/// while Rome is still an Italian power and Pataliputra rules the Ganges.
/// Marks are modern names on land that had no city then; travel drops you in the wild.
/// </summary>
public static class EarthPlaces
{
    public static readonly EarthPlace[] Cities =
    [
        // Spawn: Ptolemaic Alexandria, the Hellenistic hinge.
        new("Alexandria", "Ptolemaic Egypt", 29.90f, 31.20f, PlaceKind.Port, "Mediterranean"),
        new("Memphis", "Ptolemaic Egypt", 31.25f, 29.85f, PlaceKind.City, "Mediterranean"),
        new("Thebes on the Nile", "Ptolemaic Egypt", 32.64f, 25.72f, PlaceKind.City, "Mediterranean"),
        new("Pelusium", "Ptolemaic Egypt", 32.55f, 31.04f, PlaceKind.Port, "Mediterranean"),
        new("Naukratis", "Ptolemaic Egypt", 30.59f, 30.90f, PlaceKind.Port, "Mediterranean"),
        new("Canopus", "Ptolemaic Egypt", 30.07f, 31.31f, PlaceKind.Port, "Mediterranean"),
        new("Syene", "Ptolemaic Egypt", 32.90f, 24.09f, PlaceKind.City, "Mediterranean"),
        new("Ptolemais Hermiou", "Ptolemaic Egypt", 31.70f, 26.48f, PlaceKind.City, "Mediterranean"),
        new("Berenice", "Ptolemaic Egypt", 35.48f, 23.91f, PlaceKind.Port, "Africa"),
        new("Cyrene", "Ptolemaic Egypt", 21.85f, 32.82f, PlaceKind.City, "Mediterranean"),
        new("Carthage", "Carthage", 10.32f, 36.85f, PlaceKind.Port, "Mediterranean"),
        new("Utica", "Carthage", 10.06f, 37.06f, PlaceKind.Port, "Mediterranean"),
        new("Hadrumetum", "Carthage", 10.64f, 35.83f, PlaceKind.Port, "Mediterranean"),
        new("Leptis Magna", "Carthage", 14.29f, 32.64f, PlaceKind.Port, "Mediterranean"),
        new("Sabratha", "Carthage", 12.48f, 32.79f, PlaceKind.Port, "Mediterranean"),
        new("Hippo Regius", "Carthage", 7.75f, 36.88f, PlaceKind.Port, "Mediterranean"),
        new("Icosium", "Carthage", 3.06f, 36.77f, PlaceKind.Port, "Mediterranean"),
        new("Cirta", "Numidia", 6.61f, 36.37f, PlaceKind.City, "Mediterranean"),
        new("Tingis", "Mauritania", 5.81f, 35.78f, PlaceKind.Port, "West"),
        new("Lixus", "Mauritania", -6.11f, 35.20f, PlaceKind.Port, "West"),
        new("Gades", "Carthage", -6.29f, 36.53f, PlaceKind.Port, "West"),
        new("Malaka", "Carthage", -4.42f, 36.72f, PlaceKind.Port, "West"),
        new("Ebusus", "Carthage", 1.43f, 38.91f, PlaceKind.Port, "West"),
        new("Saguntum", "Iberia", -0.28f, 39.68f, PlaceKind.Port, "West"),
        new("Olisipo", "Lusitania", -9.14f, 38.72f, PlaceKind.Port, "West"),
        new("Numantia", "Celtiberia", -2.60f, 41.81f, PlaceKind.City, "West"),
        new("Massalia", "Massalia", 5.37f, 43.30f, PlaceKind.Port, "West"),
        new("Emporion", "Massalia", 3.12f, 42.13f, PlaceKind.Port, "West"),
        new("Entremont", "Salluvii", 5.50f, 43.55f, PlaceKind.City, "West"),
        new("Tolosa", "Volcae", 1.44f, 43.60f, PlaceKind.City, "West"),
        new("Lutetia", "Parisii", 2.35f, 48.86f, PlaceKind.City, "West"),
        new("Alesia", "Mandubii", 4.54f, 47.54f, PlaceKind.City, "West"),
        new("Bibracte", "Aedui", 4.54f, 46.92f, PlaceKind.City, "West"),
        new("Gergovia", "Arverni", 3.12f, 45.72f, PlaceKind.City, "West"),
        new("Manching", "Vindelici", 11.51f, 48.72f, PlaceKind.City, "West"),
        new("Glauberg", "Celts", 8.80f, 50.31f, PlaceKind.City, "West"),
        new("Zavist", "Boii", 14.37f, 49.97f, PlaceKind.City, "West"),
        new("Noreia", "Norici", 14.50f, 47.05f, PlaceKind.City, "West"),
        new("Biskupin", "Lusatian", 17.72f, 52.79f, PlaceKind.City, "West"),
        new("Emain Macha", "Ulaid", -6.40f, 54.35f, PlaceKind.City, "West"),
        new("Tara", "Gaels", -6.61f, 53.58f, PlaceKind.City, "West"),
        new("Rome", "Roman Republic", 12.48f, 41.89f, PlaceKind.City, "Mediterranean"),
        new("Ostia", "Roman Republic", 12.29f, 41.75f, PlaceKind.Port, "Mediterranean"),
        new("Capua", "Roman Republic", 14.21f, 41.11f, PlaceKind.City, "Mediterranean"),
        new("Praeneste", "Roman Republic", 12.89f, 41.83f, PlaceKind.City, "Mediterranean"),
        new("Tarentum", "Roman Republic", 17.24f, 40.47f, PlaceKind.Port, "Mediterranean"),
        new("Brundisium", "Roman Republic", 17.94f, 40.63f, PlaceKind.Port, "Mediterranean"),
        new("Neapolis", "Roman Republic", 14.25f, 40.85f, PlaceKind.Port, "Mediterranean"),
        new("Rhegium", "Roman Republic", 15.65f, 38.11f, PlaceKind.Port, "Mediterranean"),
        new("Croton", "Bruttii", 17.12f, 39.08f, PlaceKind.Port, "Mediterranean"),
        new("Genua", "Ligures", 8.93f, 44.41f, PlaceKind.Port, "Mediterranean"),
        new("Pisae", "Etruria", 10.40f, 43.72f, PlaceKind.Port, "Mediterranean"),
        new("Arretium", "Etruria", 11.88f, 43.46f, PlaceKind.City, "Mediterranean"),
        new("Ariminum", "Umbria", 12.57f, 44.06f, PlaceKind.Port, "Mediterranean"),
        new("Mediolanum", "Insubres", 9.19f, 45.46f, PlaceKind.City, "West"),
        new("Syracuse", "Syracuse", 15.29f, 37.07f, PlaceKind.Port, "Mediterranean"),
        new("Agrigentum", "Sicily", 13.59f, 37.31f, PlaceKind.City, "Mediterranean"),
        new("Lilybaeum", "Carthage", 12.43f, 37.80f, PlaceKind.Port, "Mediterranean"),
        new("Panormus", "Carthage", 13.36f, 38.12f, PlaceKind.Port, "Mediterranean"),
        new("Messana", "Sicily", 15.55f, 38.19f, PlaceKind.Port, "Mediterranean"),
        new("Athens", "Antigonid Macedon", 23.73f, 37.98f, PlaceKind.City, "Mediterranean"),
        new("Pella", "Antigonid Macedon", 22.52f, 40.76f, PlaceKind.City, "Mediterranean"),
        new("Thessalonica", "Antigonid Macedon", 22.94f, 40.64f, PlaceKind.Port, "Mediterranean"),
        new("Corinth", "Antigonid Macedon", 22.93f, 37.94f, PlaceKind.City, "Mediterranean"),
        new("Sparta", "Sparta", 22.43f, 37.07f, PlaceKind.City, "Mediterranean"),
        new("Thebes of Boeotia", "Boeotia", 23.32f, 38.32f, PlaceKind.City, "Mediterranean"),
        new("Argos", "Argolid", 22.73f, 37.63f, PlaceKind.City, "Mediterranean"),
        new("Chalcis", "Euboea", 23.59f, 38.46f, PlaceKind.Port, "Mediterranean"),
        new("Amphipolis", "Antigonid Macedon", 23.85f, 40.82f, PlaceKind.City, "Mediterranean"),
        new("Knossos", "Crete", 25.16f, 35.30f, PlaceKind.City, "Mediterranean"),
        new("Gortyn", "Crete", 24.95f, 35.06f, PlaceKind.City, "Mediterranean"),
        new("Rhodes", "Rhodes", 28.23f, 36.44f, PlaceKind.Port, "Mediterranean"),
        new("Salamis of Cyprus", "Cyprus", 33.90f, 35.19f, PlaceKind.Port, "Mediterranean"),
        new("Paphos", "Cyprus", 32.41f, 34.76f, PlaceKind.Port, "Mediterranean"),
        new("Ephesus", "Seleucid Empire", 27.34f, 37.94f, PlaceKind.Port, "Mediterranean"),
        new("Miletus", "Seleucid Empire", 27.28f, 37.53f, PlaceKind.Port, "Mediterranean"),
        new("Priene", "Seleucid Empire", 27.30f, 37.66f, PlaceKind.City, "Mediterranean"),
        new("Halicarnassus", "Seleucid Empire", 27.42f, 37.03f, PlaceKind.Port, "Mediterranean"),
        new("Cnidus", "Seleucid Empire", 27.37f, 36.69f, PlaceKind.Port, "Mediterranean"),
        new("Smyrna", "Seleucid Empire", 27.14f, 38.42f, PlaceKind.Port, "Mediterranean"),
        new("Sardis", "Seleucid Empire", 28.04f, 38.49f, PlaceKind.City, "Mediterranean"),
        new("Pergamon", "Pergamon", 27.18f, 39.12f, PlaceKind.City, "Mediterranean"),
        new("Cyzicus", "Mysia", 27.89f, 40.39f, PlaceKind.Port, "Mediterranean"),
        new("Byzantium", "Byzantium", 28.98f, 41.01f, PlaceKind.Port, "Mediterranean"),
        new("Chalcedon", "Bithynia", 29.03f, 40.98f, PlaceKind.Port, "Mediterranean"),
        new("Heraclea Pontica", "Pontus", 31.42f, 41.28f, PlaceKind.Port, "Near East"),
        new("Sinope", "Pontus", 35.15f, 42.03f, PlaceKind.Port, "Near East"),
        new("Amisus", "Pontus", 36.33f, 41.29f, PlaceKind.Port, "Near East"),
        new("Trapezus", "Pontus", 39.72f, 41.00f, PlaceKind.Port, "Near East"),
        new("Side", "Seleucid Empire", 31.39f, 36.77f, PlaceKind.Port, "Mediterranean"),
        new("Aspendos", "Seleucid Empire", 31.17f, 36.94f, PlaceKind.City, "Mediterranean"),
        new("Tarsus", "Seleucid Empire", 34.90f, 36.92f, PlaceKind.City, "Near East"),
        new("Ancyra", "Galatia", 32.85f, 39.93f, PlaceKind.City, "Near East"),
        new("Mytilene", "Lesbos", 26.55f, 39.11f, PlaceKind.Port, "Mediterranean"),
        new("Olbia", "Bosporan Kingdom", 30.78f, 46.69f, PlaceKind.Port, "Steppe"),
        new("Panticapaeum", "Bosporan Kingdom", 36.47f, 45.35f, PlaceKind.Port, "Steppe"),
        new("Phanagoria", "Bosporan Kingdom", 36.97f, 45.28f, PlaceKind.Port, "Steppe"),
        new("Chersonesus", "Bosporan Kingdom", 33.49f, 44.61f, PlaceKind.Port, "Steppe"),
        new("Tanais", "Bosporan Kingdom", 39.23f, 47.20f, PlaceKind.Port, "Steppe"),
        new("Dioscurias", "Colchis", 41.02f, 43.00f, PlaceKind.Port, "Steppe"),
        new("Antioch", "Seleucid Empire", 36.16f, 36.20f, PlaceKind.City, "Near East"),
        new("Tyre", "Seleucid Empire", 35.19f, 33.27f, PlaceKind.Port, "Near East"),
        new("Sidon", "Seleucid Empire", 35.37f, 33.56f, PlaceKind.Port, "Near East"),
        new("Damascus", "Seleucid Empire", 36.28f, 33.51f, PlaceKind.City, "Near East"),
        new("Palmyra", "Tadmor", 38.27f, 34.55f, PlaceKind.City, "Near East"),
        new("Baalbek", "Seleucid Empire", 36.20f, 34.01f, PlaceKind.City, "Near East"),
        new("Jerusalem", "Ptolemaic Egypt", 35.22f, 31.77f, PlaceKind.City, "Near East"),
        new("Gaza", "Ptolemaic Egypt", 34.47f, 31.50f, PlaceKind.Port, "Near East"),
        new("Ashkelon", "Ptolemaic Egypt", 34.55f, 31.67f, PlaceKind.Port, "Near East"),
        new("Petra", "Nabataea", 35.44f, 30.33f, PlaceKind.City, "Near East"),
        new("Dedan", "Lihyan", 37.92f, 26.62f, PlaceKind.City, "Near East"),
        new("Gerrha", "Arabia", 50.20f, 26.30f, PlaceKind.Port, "Near East"),
        new("Tylos", "Arabia", 50.58f, 26.23f, PlaceKind.Port, "Near East"),
        new("Babylon", "Seleucid Empire", 44.42f, 32.54f, PlaceKind.City, "Near East"),
        new("Seleucia on the Tigris", "Seleucid Empire", 44.52f, 33.09f, PlaceKind.City, "Near East"),
        new("Uruk", "Seleucid Empire", 45.64f, 31.32f, PlaceKind.City, "Near East"),
        new("Nippur", "Seleucid Empire", 45.23f, 32.13f, PlaceKind.City, "Near East"),
        new("Assur", "Seleucid Empire", 43.26f, 35.46f, PlaceKind.City, "Near East"),
        new("Arbela", "Seleucid Empire", 44.01f, 36.19f, PlaceKind.City, "Near East"),
        new("Nisibis", "Seleucid Empire", 41.22f, 37.07f, PlaceKind.City, "Near East"),
        new("Harran", "Seleucid Empire", 39.03f, 36.86f, PlaceKind.City, "Near East"),
        new("Susa", "Seleucid Empire", 48.25f, 32.19f, PlaceKind.City, "Near East"),
        new("Ecbatana", "Seleucid Empire", 48.52f, 34.80f, PlaceKind.City, "Near East"),
        new("Rhages", "Seleucid Empire", 51.44f, 35.60f, PlaceKind.City, "Near East"),
        new("Aspadana", "Seleucid Empire", 51.67f, 32.65f, PlaceKind.City, "Near East"),
        new("Tushpa", "Armenia", 43.34f, 38.50f, PlaceKind.City, "Near East"),
        new("Erebuni", "Armenia", 44.53f, 40.18f, PlaceKind.City, "Near East"),
        new("Bactra", "Seleucid Empire", 66.97f, 36.76f, PlaceKind.City, "Steppe"),
        new("Maracanda", "Seleucid Empire", 66.96f, 39.65f, PlaceKind.City, "Steppe"),
        new("Merv", "Seleucid Empire", 62.17f, 37.66f, PlaceKind.City, "Steppe"),
        new("Nisa", "Parthia", 58.19f, 37.97f, PlaceKind.City, "Steppe"),
        new("Alexandria Aria", "Seleucid Empire", 62.19f, 34.34f, PlaceKind.City, "Steppe"),
        new("Alexandria Arachosia", "Seleucid Empire", 65.72f, 31.62f, PlaceKind.City, "Steppe"),
        new("Alexandria Eschate", "Seleucid Empire", 69.63f, 40.28f, PlaceKind.City, "Steppe"),
        new("Ai-Khanoum", "Seleucid Empire", 69.25f, 37.17f, PlaceKind.City, "Steppe"),
        new("Pushkalavati", "Maurya", 71.58f, 34.16f, PlaceKind.City, "India"),
        new("Meroe", "Kush", 33.73f, 16.94f, PlaceKind.City, "Africa"),
        new("Napata", "Kush", 31.83f, 18.53f, PlaceKind.City, "Africa"),
        new("Yeha", "Dmt", 39.17f, 14.28f, PlaceKind.City, "Africa"),
        new("Garama", "Garamantes", 13.06f, 26.54f, PlaceKind.City, "Africa"),
        new("Jenne-Jeno", "Niger bend", -4.54f, 13.89f, PlaceKind.City, "Africa"),
        new("Marib", "Saba", 45.32f, 15.43f, PlaceKind.City, "Africa"),
        new("Shabwa", "Hadhramaut", 46.83f, 15.37f, PlaceKind.City, "Africa"),
        new("Adulis", "Saba", 39.65f, 15.25f, PlaceKind.Port, "Africa"),
        new("Pataliputra", "Maurya", 85.01f, 25.61f, PlaceKind.City, "India"),
        new("Taxila", "Maurya", 72.83f, 33.74f, PlaceKind.City, "India"),
        new("Indraprastha", "Maurya", 77.23f, 28.61f, PlaceKind.City, "India"),
        new("Ujjain", "Maurya", 75.78f, 23.18f, PlaceKind.City, "India"),
        new("Vidisha", "Maurya", 77.81f, 23.53f, PlaceKind.City, "India"),
        new("Mathura", "Maurya", 77.68f, 27.49f, PlaceKind.City, "India"),
        new("Sravasti", "Maurya", 82.05f, 27.52f, PlaceKind.City, "India"),
        new("Ayodhya", "Maurya", 82.20f, 26.80f, PlaceKind.City, "India"),
        new("Kausambi", "Maurya", 81.31f, 25.34f, PlaceKind.City, "India"),
        new("Varanasi", "Maurya", 83.01f, 25.32f, PlaceKind.City, "India"),
        new("Rajagriha", "Maurya", 85.42f, 25.03f, PlaceKind.City, "India"),
        new("Vaishali", "Maurya", 85.13f, 25.99f, PlaceKind.City, "India"),
        new("Champa", "Maurya", 87.01f, 25.25f, PlaceKind.City, "India"),
        new("Pundranagara", "Maurya", 89.35f, 24.96f, PlaceKind.City, "India"),
        new("Tosali", "Maurya", 85.85f, 20.23f, PlaceKind.City, "India"),
        new("Tamralipti", "Maurya", 87.93f, 22.32f, PlaceKind.Port, "India"),
        new("Bharukaccha", "Maurya", 72.99f, 21.70f, PlaceKind.Port, "India"),
        new("Sopara", "Maurya", 72.80f, 19.42f, PlaceKind.Port, "India"),
        new("Pratishthana", "Satavahana", 75.39f, 19.48f, PlaceKind.City, "India"),
        new("Dhanyakataka", "Andhra", 80.40f, 16.57f, PlaceKind.City, "India"),
        new("Kanchipuram", "Chola", 79.70f, 12.83f, PlaceKind.City, "India"),
        new("Madurai", "Pandya", 78.12f, 9.93f, PlaceKind.City, "India"),
        new("Korkai", "Pandya", 78.63f, 8.67f, PlaceKind.Port, "India"),
        new("Muziris", "Chera", 76.21f, 10.16f, PlaceKind.Port, "India"),
        new("Anuradhapura", "Anuradhapura", 80.40f, 8.35f, PlaceKind.City, "India"),
        new("Xianyang", "Qin", 108.72f, 34.34f, PlaceKind.City, "East Asia"),
        new("Handan", "Zhao", 114.48f, 36.62f, PlaceKind.City, "East Asia"),
        new("Linzi", "Qi", 118.35f, 36.81f, PlaceKind.City, "East Asia"),
        new("Ying", "Chu", 112.18f, 30.36f, PlaceKind.City, "East Asia"),
        new("Jicheng", "Yan", 116.40f, 39.92f, PlaceKind.City, "East Asia"),
        new("Luoyang", "Zhou remnant", 112.45f, 34.62f, PlaceKind.City, "East Asia"),
        new("Daliang", "Wei", 114.35f, 34.79f, PlaceKind.City, "East Asia"),
        new("Xinzheng", "Han", 113.74f, 34.40f, PlaceKind.City, "East Asia"),
        new("Jinyang", "Zhao", 112.55f, 37.87f, PlaceKind.City, "East Asia"),
        new("Qufu", "Lu", 116.99f, 35.60f, PlaceKind.City, "East Asia"),
        new("Shouchun", "Chu", 116.98f, 32.57f, PlaceKind.City, "East Asia"),
        new("Ye of Zhao", "Zhao", 114.50f, 36.32f, PlaceKind.City, "East Asia"),
        new("Wu", "Wu", 120.62f, 31.30f, PlaceKind.City, "East Asia"),
        new("Kuaiji", "Yue", 120.58f, 30.00f, PlaceKind.City, "East Asia"),
        new("Chengdu", "Shu", 104.06f, 30.67f, PlaceKind.City, "East Asia"),
        new("Panyu", "Nanyue", 113.26f, 23.13f, PlaceKind.Port, "East Asia"),
        new("Minyue", "Minyue", 119.30f, 26.08f, PlaceKind.City, "East Asia"),
        new("Dian", "Dian", 102.71f, 24.88f, PlaceKind.City, "East Asia"),
        new("Xiangping", "Yan", 123.24f, 41.27f, PlaceKind.City, "East Asia"),
        new("Wanggeom", "Gojoseon", 125.75f, 39.03f, PlaceKind.City, "East Asia"),
        new("Co Loa", "Au Lac", 105.87f, 21.14f, PlaceKind.City, "East Asia"),
        new("Yoshinogari", "Yayoi", 130.22f, 33.32f, PlaceKind.City, "East Asia"),
        new("Monte Alban", "Zapotec", -96.80f, 17.04f, PlaceKind.City, "Americas"),
        new("Cuicuilco", "Basin of Mexico", -99.18f, 19.30f, PlaceKind.City, "Americas"),
        new("El Mirador", "Maya", -89.92f, 17.75f, PlaceKind.City, "Americas"),
        new("Tikal", "Maya", -89.63f, 17.22f, PlaceKind.City, "Americas"),
        new("Nakbe", "Maya", -89.83f, 17.82f, PlaceKind.City, "Americas"),
        new("Tres Zapotes", "Olmec remnant", -95.15f, 18.47f, PlaceKind.City, "Americas"),
        new("Kaminaljuyu", "Maya", -90.55f, 14.63f, PlaceKind.City, "Americas"),
        new("Chavin", "Chavin", -77.18f, -9.59f, PlaceKind.City, "Americas"),
        new("Paracas", "Paracas", -76.26f, -13.84f, PlaceKind.City, "Americas"),
        new("Chiripa", "Titicaca", -68.88f, -16.17f, PlaceKind.City, "Americas")
    ];

    public static readonly EarthPlace[] Sites =
    [
        new("Siwa of Amun", "Ptolemaic Egypt", 25.55f, 29.20f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Delphi", "Antigonid Macedon", 22.50f, 38.48f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Olympia", "Elis", 21.63f, 37.64f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Dodona", "Epirus", 20.79f, 39.55f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Didyma", "Seleucid Empire", 27.26f, 37.39f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Epidaurus", "Argolid", 23.13f, 37.60f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Eleusis", "Attica", 23.54f, 38.04f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Delos", "Cyclades", 25.27f, 37.40f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Cumae", "Roman Republic", 14.05f, 40.85f, PlaceKind.Sanctuary, "Mediterranean"),
        new("Giza", "Ptolemaic Egypt", 31.13f, 29.98f, PlaceKind.Ruin, "Mediterranean"),
        new("Valley of the Kings", "Ptolemaic Egypt", 32.60f, 25.74f, PlaceKind.Ruin, "Mediterranean"),
        new("Hawara labyrinth", "Ptolemaic Egypt", 30.90f, 29.27f, PlaceKind.Ruin, "Mediterranean"),
        new("Nineveh", "Assyria", 43.16f, 36.36f, PlaceKind.Ruin, "Near East"),
        new("Ur", "Sumer", 46.10f, 30.96f, PlaceKind.Ruin, "Near East"),
        new("Persepolis", "Seleucid Empire", 52.89f, 29.93f, PlaceKind.Ruin, "Near East"),
        new("Pasargadae", "Seleucid Empire", 53.17f, 30.20f, PlaceKind.Ruin, "Near East"),
        new("Bodh Gaya", "Maurya", 84.99f, 24.70f, PlaceKind.Sanctuary, "India"),
        new("Sarnath", "Maurya", 83.02f, 25.38f, PlaceKind.Sanctuary, "India"),
        new("Sanchi", "Maurya", 77.74f, 23.48f, PlaceKind.Sanctuary, "India"),
        new("Kailash", "Zhangzhung", 81.31f, 31.07f, PlaceKind.Sanctuary, "India"),
        new("Sanxingdui", "Shu", 104.20f, 30.99f, PlaceKind.Ruin, "East Asia"),
        new("Stonehenge", "Britons", -1.83f, 51.18f, PlaceKind.Ruin, "West"),
        new("Newgrange", "Gaels", -6.61f, 53.69f, PlaceKind.Ruin, "West"),
        new("Carnac", "Veneti", -3.08f, 47.59f, PlaceKind.Ruin, "West"),
        new("Su Nuraxi", "Sardinia", 8.83f, 39.72f, PlaceKind.Ruin, "Mediterranean"),
        new("Chavin de Huantar", "Chavin", -77.18f, -9.59f, PlaceKind.Sanctuary, "Americas")
    ];

    /// <summary>Modern names on land that had no city around 300 BCE. Fast travel only.</summary>
    public static readonly EarthPlace[] Marks =
    [
        new("London", "now", -0.13f, 51.51f, PlaceKind.Mark, "West"),
        new("York", "now", -1.08f, 53.96f, PlaceKind.Mark, "West"),
        new("Edinburgh", "now", -3.19f, 55.95f, PlaceKind.Mark, "West"),
        new("Amsterdam", "now", 4.90f, 52.37f, PlaceKind.Mark, "West"),
        new("Brussels", "now", 4.35f, 50.85f, PlaceKind.Mark, "West"),
        new("Hamburg", "now", 9.99f, 53.55f, PlaceKind.Mark, "West"),
        new("Berlin", "now", 13.41f, 52.52f, PlaceKind.Mark, "West"),
        new("Copenhagen", "now", 12.57f, 55.68f, PlaceKind.Mark, "West"),
        new("Stockholm", "now", 18.07f, 59.33f, PlaceKind.Mark, "West"),
        new("Oslo", "now", 10.75f, 59.91f, PlaceKind.Mark, "West"),
        new("Helsinki", "now", 24.94f, 60.17f, PlaceKind.Mark, "West"),
        new("Warsaw", "now", 21.01f, 52.23f, PlaceKind.Mark, "West"),
        new("Krakow", "now", 19.94f, 50.06f, PlaceKind.Mark, "West"),
        new("Prague", "now", 14.44f, 50.09f, PlaceKind.Mark, "West"),
        new("Vienna", "now", 16.37f, 48.21f, PlaceKind.Mark, "West"),
        new("Budapest", "now", 19.04f, 47.50f, PlaceKind.Mark, "West"),
        new("Belgrade", "now", 20.46f, 44.82f, PlaceKind.Mark, "West"),
        new("Bucharest", "now", 26.10f, 44.43f, PlaceKind.Mark, "West"),
        new("Kiev", "now", 30.52f, 50.45f, PlaceKind.Mark, "Steppe"),
        new("Minsk", "now", 27.56f, 53.90f, PlaceKind.Mark, "West"),
        new("Riga", "now", 24.11f, 56.95f, PlaceKind.Mark, "West"),
        new("Moscow", "now", 37.62f, 55.76f, PlaceKind.Mark, "Steppe"),
        new("Novgorod", "now", 31.27f, 58.52f, PlaceKind.Mark, "Steppe"),
        new("Saint Petersburg", "now", 30.31f, 59.93f, PlaceKind.Mark, "Steppe"),
        new("Kazan", "now", 49.11f, 55.79f, PlaceKind.Mark, "Steppe"),
        new("Lyon", "now", 4.84f, 45.76f, PlaceKind.Mark, "West"),
        new("Venice", "now", 12.34f, 45.44f, PlaceKind.Mark, "Mediterranean"),
        new("Tbilisi", "now", 44.79f, 41.72f, PlaceKind.Mark, "Near East"),
        new("Lagos", "now", 3.38f, 6.45f, PlaceKind.Mark, "Africa"),
        new("Accra", "now", -0.19f, 5.56f, PlaceKind.Mark, "Africa"),
        new("Abidjan", "now", -4.03f, 5.32f, PlaceKind.Mark, "Africa"),
        new("Dakar", "now", -17.44f, 14.69f, PlaceKind.Mark, "Africa"),
        new("Bamako", "now", -8.00f, 12.64f, PlaceKind.Mark, "Africa"),
        new("Casablanca", "now", -7.62f, 33.59f, PlaceKind.Mark, "Africa"),
        new("Khartoum", "now", 32.53f, 15.50f, PlaceKind.Mark, "Africa"),
        new("Addis Ababa", "now", 38.74f, 9.03f, PlaceKind.Mark, "Africa"),
        new("Nairobi", "now", 36.82f, -1.29f, PlaceKind.Mark, "Africa"),
        new("Kampala", "now", 32.58f, 0.35f, PlaceKind.Mark, "Africa"),
        new("Mogadishu", "now", 45.34f, 2.05f, PlaceKind.Mark, "Africa"),
        new("Dar es Salaam", "now", 39.21f, -6.79f, PlaceKind.Mark, "Africa"),
        new("Kinshasa", "now", 15.27f, -4.32f, PlaceKind.Mark, "Africa"),
        new("Luanda", "now", 13.23f, -8.84f, PlaceKind.Mark, "Africa"),
        new("Johannesburg", "now", 28.05f, -26.20f, PlaceKind.Mark, "Africa"),
        new("Cape Town", "now", 18.42f, -33.93f, PlaceKind.Mark, "Africa"),
        new("Durban", "now", 31.02f, -29.86f, PlaceKind.Mark, "Africa"),
        new("Maputo", "now", 32.57f, -25.97f, PlaceKind.Mark, "Africa"),
        new("Harare", "now", 31.05f, -17.83f, PlaceKind.Mark, "Africa"),
        new("Lusaka", "now", 28.28f, -15.42f, PlaceKind.Mark, "Africa"),
        new("Windhoek", "now", 17.08f, -22.56f, PlaceKind.Mark, "Africa"),
        new("Antananarivo", "now", 47.51f, -18.88f, PlaceKind.Mark, "Africa"),
        new("Karachi", "now", 67.00f, 24.86f, PlaceKind.Mark, "India"),
        new("Lahore", "now", 74.36f, 31.55f, PlaceKind.Mark, "India"),
        new("Bengaluru", "now", 77.59f, 12.97f, PlaceKind.Mark, "India"),
        new("Hyderabad", "now", 78.49f, 17.39f, PlaceKind.Mark, "India"),
        new("Dhaka", "now", 90.41f, 23.81f, PlaceKind.Mark, "India"),
        new("Kathmandu", "now", 85.32f, 27.72f, PlaceKind.Mark, "India"),
        new("Colombo", "now", 79.86f, 6.93f, PlaceKind.Mark, "India"),
        new("Kabul", "now", 69.17f, 34.53f, PlaceKind.Mark, "Steppe"),
        new("Tashkent", "now", 69.24f, 41.30f, PlaceKind.Mark, "Steppe"),
        new("Almaty", "now", 76.95f, 43.24f, PlaceKind.Mark, "Steppe"),
        new("Ulaanbaatar", "now", 106.91f, 47.92f, PlaceKind.Mark, "Steppe"),
        new("Riyadh", "now", 46.68f, 24.71f, PlaceKind.Mark, "Near East"),
        new("Jeddah", "now", 39.17f, 21.49f, PlaceKind.Mark, "Near East"),
        new("Dubai", "now", 55.27f, 25.20f, PlaceKind.Mark, "Near East"),
        new("Muscat", "now", 58.54f, 23.59f, PlaceKind.Mark, "Near East"),
        new("Doha", "now", 51.53f, 25.29f, PlaceKind.Mark, "Near East"),
        new("Seoul", "now", 126.98f, 37.57f, PlaceKind.Mark, "East Asia"),
        new("Busan", "now", 129.08f, 35.18f, PlaceKind.Mark, "East Asia"),
        new("Tokyo", "now", 139.69f, 35.68f, PlaceKind.Mark, "East Asia"),
        new("Osaka", "now", 135.50f, 34.69f, PlaceKind.Mark, "East Asia"),
        new("Kyoto", "now", 135.77f, 35.01f, PlaceKind.Mark, "East Asia"),
        new("Sapporo", "now", 141.35f, 43.06f, PlaceKind.Mark, "East Asia"),
        new("Taipei", "now", 121.57f, 25.03f, PlaceKind.Mark, "East Asia"),
        new("Hong Kong", "now", 114.17f, 22.32f, PlaceKind.Mark, "East Asia"),
        new("Nanjing", "now", 118.80f, 32.06f, PlaceKind.Mark, "East Asia"),
        new("Wuhan", "now", 114.31f, 30.59f, PlaceKind.Mark, "East Asia"),
        new("Harbin", "now", 126.64f, 45.75f, PlaceKind.Mark, "East Asia"),
        new("Vladivostok", "now", 131.89f, 43.12f, PlaceKind.Mark, "East Asia"),
        new("Yangon", "now", 96.16f, 16.80f, PlaceKind.Mark, "East Asia"),
        new("Bangkok", "now", 100.50f, 13.76f, PlaceKind.Mark, "East Asia"),
        new("Phnom Penh", "now", 104.92f, 11.56f, PlaceKind.Mark, "East Asia"),
        new("Ho Chi Minh", "now", 106.63f, 10.82f, PlaceKind.Mark, "East Asia"),
        new("Kuala Lumpur", "now", 101.69f, 3.14f, PlaceKind.Mark, "East Asia"),
        new("Singapore", "now", 103.82f, 1.35f, PlaceKind.Mark, "East Asia"),
        new("Jakarta", "now", 106.85f, -6.21f, PlaceKind.Mark, "East Asia"),
        new("Surabaya", "now", 112.75f, -7.26f, PlaceKind.Mark, "East Asia"),
        new("Manila", "now", 120.98f, 14.60f, PlaceKind.Mark, "East Asia"),
        new("New York", "now", -74.01f, 40.71f, PlaceKind.Mark, "Americas"),
        new("Boston", "now", -71.06f, 42.36f, PlaceKind.Mark, "Americas"),
        new("Philadelphia", "now", -75.17f, 39.95f, PlaceKind.Mark, "Americas"),
        new("Washington", "now", -77.04f, 38.91f, PlaceKind.Mark, "Americas"),
        new("Chicago", "now", -87.63f, 41.88f, PlaceKind.Mark, "Americas"),
        new("Detroit", "now", -83.05f, 42.33f, PlaceKind.Mark, "Americas"),
        new("Atlanta", "now", -84.39f, 33.75f, PlaceKind.Mark, "Americas"),
        new("Miami", "now", -80.19f, 25.76f, PlaceKind.Mark, "Americas"),
        new("New Orleans", "now", -90.07f, 29.95f, PlaceKind.Mark, "Americas"),
        new("Dallas", "now", -96.80f, 32.78f, PlaceKind.Mark, "Americas"),
        new("Houston", "now", -95.37f, 29.76f, PlaceKind.Mark, "Americas"),
        new("Denver", "now", -104.99f, 39.74f, PlaceKind.Mark, "Americas"),
        new("Phoenix", "now", -112.07f, 33.45f, PlaceKind.Mark, "Americas"),
        new("Los Angeles", "now", -118.24f, 34.05f, PlaceKind.Mark, "Americas"),
        new("San Francisco", "now", -122.42f, 37.77f, PlaceKind.Mark, "Americas"),
        new("Seattle", "now", -122.33f, 47.61f, PlaceKind.Mark, "Americas"),
        new("Vancouver", "now", -123.12f, 49.28f, PlaceKind.Mark, "Americas"),
        new("Toronto", "now", -79.38f, 43.65f, PlaceKind.Mark, "Americas"),
        new("Montreal", "now", -73.57f, 45.50f, PlaceKind.Mark, "Americas"),
        new("Calgary", "now", -114.07f, 51.05f, PlaceKind.Mark, "Americas"),
        new("Winnipeg", "now", -97.14f, 49.90f, PlaceKind.Mark, "Americas"),
        new("Anchorage", "now", -149.90f, 61.22f, PlaceKind.Mark, "Americas"),
        new("Honolulu", "now", -157.86f, 21.31f, PlaceKind.Mark, "Pacific"),
        new("Havana", "now", -82.38f, 23.13f, PlaceKind.Mark, "Americas"),
        new("Kingston", "now", -76.79f, 17.97f, PlaceKind.Mark, "Americas"),
        new("San Juan", "now", -66.11f, 18.47f, PlaceKind.Mark, "Americas"),
        new("Panama City", "now", -79.53f, 8.98f, PlaceKind.Mark, "Americas"),
        new("Guadalajara", "now", -103.35f, 20.66f, PlaceKind.Mark, "Americas"),
        new("Monterrey", "now", -100.32f, 25.67f, PlaceKind.Mark, "Americas"),
        new("Bogota", "now", -74.07f, 4.71f, PlaceKind.Mark, "Americas"),
        new("Caracas", "now", -66.90f, 10.49f, PlaceKind.Mark, "Americas"),
        new("Quito", "now", -78.47f, -0.23f, PlaceKind.Mark, "Americas"),
        new("Lima", "now", -77.04f, -12.05f, PlaceKind.Mark, "Americas"),
        new("La Paz", "now", -68.15f, -16.50f, PlaceKind.Mark, "Americas"),
        new("Sao Paulo", "now", -46.63f, -23.55f, PlaceKind.Mark, "Americas"),
        new("Rio de Janeiro", "now", -43.17f, -22.91f, PlaceKind.Mark, "Americas"),
        new("Salvador", "now", -38.50f, -12.97f, PlaceKind.Mark, "Americas"),
        new("Recife", "now", -34.88f, -8.05f, PlaceKind.Mark, "Americas"),
        new("Manaus", "now", -60.02f, -3.12f, PlaceKind.Mark, "Americas"),
        new("Brasilia", "now", -47.88f, -15.79f, PlaceKind.Mark, "Americas"),
        new("Buenos Aires", "now", -58.38f, -34.60f, PlaceKind.Mark, "Americas"),
        new("Montevideo", "now", -56.16f, -34.90f, PlaceKind.Mark, "Americas"),
        new("Santiago", "now", -70.67f, -33.45f, PlaceKind.Mark, "Americas"),
        new("Asuncion", "now", -57.64f, -25.26f, PlaceKind.Mark, "Americas"),
        new("Sydney", "now", 151.21f, -33.87f, PlaceKind.Mark, "Pacific"),
        new("Melbourne", "now", 144.96f, -37.81f, PlaceKind.Mark, "Pacific"),
        new("Brisbane", "now", 153.03f, -27.47f, PlaceKind.Mark, "Pacific"),
        new("Perth", "now", 115.86f, -31.95f, PlaceKind.Mark, "Pacific"),
        new("Adelaide", "now", 138.60f, -34.93f, PlaceKind.Mark, "Pacific"),
        new("Auckland", "now", 174.76f, -36.85f, PlaceKind.Mark, "Pacific"),
        new("Wellington", "now", 174.78f, -41.29f, PlaceKind.Mark, "Pacific"),
        new("Port Moresby", "now", 147.18f, -9.44f, PlaceKind.Mark, "Pacific"),
        new("Suva", "now", 178.44f, -18.14f, PlaceKind.Mark, "Pacific"),
        new("Papeete", "now", -149.57f, -17.54f, PlaceKind.Mark, "Pacific"),
        new("Reykjavik", "now", -21.94f, 64.15f, PlaceKind.Mark, "West")
    ];

    public static int CityCount => Cities.Length;
    public static int MarkCount => Marks.Length;
    public static int SiteCount => Sites.Length;
    public static int StopCount => Cities.Length + Marks.Length;

    public static int Alexandria => 0;

    public static bool IsHistoric(int index) => (uint)index < (uint)Cities.Length;

    public static bool IsMark(int index) => (uint)(index - Cities.Length) < (uint)Marks.Length;

    public static EarthPlace StopAt(int index)
        => index < Cities.Length ? Cities[index] : Marks[index - Cities.Length];
}
