<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CharacterStudio</RootNamespace>
    <AssemblyName>CharacterStudio</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ember.Engine\Ember.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\TextureCoordinateTest.glb" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
